// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpurYBJ_GgVqpuZwXgC06OvOhgUXXsxOY',
    appId: '1:798557469278:web:686178762c8b820e1212cf',
    messagingSenderId: '798557469278',
    projectId: 'techwiz-6a7de',
    authDomain: 'techwiz-6a7de.firebaseapp.com',
    databaseURL: 'https://techwiz-6a7de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techwiz-6a7de.firebasestorage.app',
    measurementId: 'G-V3GW3959T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeKfrlIpJ6Ss8BdFlVY29-hozUxWPiA5A',
    appId: '1:798557469278:android:59cc3a53920063791212cf',
    messagingSenderId: '798557469278',
    projectId: 'techwiz-6a7de',
    databaseURL: 'https://techwiz-6a7de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techwiz-6a7de.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACquc8lkQMk7b8vAYki99LnWBohaf5jdU',
    appId: '1:798557469278:ios:5ec7625f99eab09c1212cf',
    messagingSenderId: '798557469278',
    projectId: 'techwiz-6a7de',
    databaseURL: 'https://techwiz-6a7de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techwiz-6a7de.firebasestorage.app',
    iosBundleId: 'com.example.techwiz7',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACquc8lkQMk7b8vAYki99LnWBohaf5jdU',
    appId: '1:798557469278:ios:5ec7625f99eab09c1212cf',
    messagingSenderId: '798557469278',
    projectId: 'techwiz-6a7de',
    databaseURL: 'https://techwiz-6a7de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techwiz-6a7de.firebasestorage.app',
    iosBundleId: 'com.example.techwiz7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpurYBJ_GgVqpuZwXgC06OvOhgUXXsxOY',
    appId: '1:798557469278:web:6a50c99a8cadee021212cf',
    messagingSenderId: '798557469278',
    projectId: 'techwiz-6a7de',
    authDomain: 'techwiz-6a7de.firebaseapp.com',
    databaseURL: 'https://techwiz-6a7de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'techwiz-6a7de.firebasestorage.app',
    measurementId: 'G-5EWBKDVJDV',
  );
}
